defaults:
  - process: process_2
  - segment: KMeans
  - _self_

data:
  raw: data/raw/marketing_campaign.csv
  scaled: data/intermediate/scaled_data.pkl
  pca: data/intermediate/pca_data.pkl 
  final: data/final/segmented_data.pkl

scaler: scaler/standard_scaler.pkl
model: model/kmeans.pkl

elbow_metric: silhouette

image:
  elbow: image/elbow.png
  clusters: image/cluster.png

pca:
  n_components: 3
  columns:
    - col1
    - col2
    - col3