name: Test code and app
on:
  pull_request:
    paths:
      - conf/**
      - src/**
      - tests/**
      - params.yaml
      
jobs:
  test_model:
    name: Test processed code and model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install packages
        run: poetry install

      - name: Pull data and model
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: poetry run dvc pull -r read-write

      - name: Run tests
        run: poetry run pytest 

      - name: Evaluate model
        run: poetry run dvc exp run evaluate

      - name: Iterative CML setup
        uses: iterative/setup-cml@v1
      
      - name: Create CML report
        run: |
          # Add the metrics to the report
          cat dvclive/metrics.json >> report.md
          # Add the parameters to the report
          echo -e >> report.md
          cat dvclive/params.yaml >> report.md 